import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "Men Kurta",
    make: "FABWAX",
    imgUrl:
      "https://ik.imagekit.io/tqp4crltjb5/Swadeshi-images/MenKurtaandPyjamaSetCottonBlend_6gDlHyA97.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647795036384",
    description: "Men Kurta and Pyjama Set Cotton Blend Black",
    originalPrice: "1599",
    discountedPrice: "629",
    rating: "3.5",
    totalRatings: "154",
    isAvailable: true,
    isWishlisted: false,
    isAddedToCart: false,
    availableSize: ["XS", "S", "L", "XL", "XXL", "3XL"],
    categoryName: "men",
    count: "10",
  },
  {
    _id: uuid(),
    name: "Men Kurta",
    make: "Enmozz",
    imgUrl:
      "https://ik.imagekit.io/tqp4crltjb5/Swadeshi-images/MenKurtaandPyjamaSetCottonBlendPink_gHgze7725.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647795033980",
    description: "Men Kurta and Pyjama Set Cotton Blend Pink",
    originalPrice: "2199",
    discountedPrice: "389",
    rating: "4.1",
    totalRatings: "657",
    isAvailable: true,
    isWishlisted: false,
    isAddedToCart: false,
    availableSize: ["XS", "S", "L", "XL", "XXL", "3XL"],
    categoryName: "men",
    count: "10",
  },
  {
    _id: uuid(),
    name: "Men Kurta",
    make: "MANYAVAR",
    imgUrl:
      "https://ik.imagekit.io/tqp4crltjb5/Swadeshi-images/MenKurtaandPyjamaSetCottonBlendCream_3_g-gIQDQ.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647795033923",
    description: "Men Kurta and Pyjama Set Cotton Blend Cream",
    originalPrice: "3499",
    discountedPrice: "2999",
    rating: "4.2",
    totalRatings: "16",
    isAvailable: true,
    isWishlisted: false,
    isAddedToCart: false,
    availableSize: ["XS", "S", "L", "XL", "XXL", "3XL"],
    categoryName: "men",
    count: "10",
  },
  {
    _id: uuid(),
    name: "Men Kurta",
    make: "Sanwara",
    imgUrl:
      "https://ik.imagekit.io/tqp4crltjb5/Swadeshi-images/MenKurtaandChuridarSetArtSilk_Z0oVOoO5G.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647795034581",
    description: "Men Kurta and Churidar Set Art Silk",
    originalPrice: "6699",
    discountedPrice: "4019",
    rating: "5",
    totalRatings: "1",
    isAvailable: true,
    isWishlisted: false,
    isAddedToCart: false,
    availableSize: ["XS", "S", "L", "XL", "XXL", "3XL"],
    categoryName: "men",
    count: "10",
  },
  {
    _id: uuid(),
    name: "Men Sherwani",
    make: "SG RAJASAHAB",
    imgUrl:
      "https://ik.imagekit.io/tqp4crltjb5/Swadeshi-images/MenSherwaniandChuridarSetRawSilk_ojVEMOZV8.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647795035871",
    description: "Men Sherwani and Churidar Set Raw Silk",
    originalPrice: "10999",
    discountedPrice: "3960",
    rating: "4.3",
    totalRatings: "8",
    isAvailable: true,
    isWishlisted: false,
    isAddedToCart: false,
    availableSize: ["XS", "S", "L", "XL", "XXL", "3XL"],
    categoryName: "men",
    count: "10",
  },
  {
    _id: uuid(),
    name: "Men Kurta",
    make: "MANYAVAR",
    imgUrl:
      "https://ik.imagekit.io/tqp4crltjb5/Swadeshi-images/MenKurtaandChuridarSetCottonBlend_w6yboo-nq.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647795035587",
    description: "Men Kurta and Churidar Set Cotton Blend",
    originalPrice: "2999",
    discountedPrice: "2499",
    rating: "4.2",
    totalRatings: "25",
    isAvailable: true,
    isWishlisted: false,
    isAddedToCart: false,
    availableSize: ["XS", "S", "L", "XL", "XXL", "3XL"],
    categoryName: "men",
    count: "10",
  },
  {
    _id: uuid(),
    name: "Boys Pyjama",
    make: "Vesh",
    imgUrl:
      "https://ik.imagekit.io/tqp4crltjb5/Swadeshi-images/BoysFestivePartyKurtaandPyjamaSet_W_Qxi2r3t.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647795037376",
    description:
      "Boys Festive & Party Kurta and Pyjama Set  (Light Green Pack of 1)",
    originalPrice: "999",
    discountedPrice: "314",
    rating: "4.0",
    totalRatings: "9042",
    isAvailable: true,
    isWishlisted: false,
    isAddedToCart: false,
    availableSize: ["XS", "S", "L"],
    categoryName: "boys",
    count: "10",
  },
  {
    _id: uuid(),
    name: "Boys Pyjama",
    make: "Ashika",
    imgUrl:
      "https://ik.imagekit.io/tqp4crltjb5/Swadeshi-images/BoysFestivePartyKurtaandPyjamaSetBlue_1zUvH5ZFH.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647795033955",
    description: "Boys Festive & Party Kurta and Pyjama Set Blue",
    originalPrice: "4000",
    discountedPrice: "2500",
    rating: "3.0",
    totalRatings: "17",
    isAvailable: true,
    isWishlisted: false,
    isAddedToCart: false,
    availableSize: ["XS", "S", "L"],
    categoryName: "boys",
    count: "10",
  },
  {
    _id: uuid(),
    name: "Boys Pyjama",
    make: "RKW",
    imgUrl:
      "https://ik.imagekit.io/tqp4crltjb5/Swadeshi-images/BoysFestivePartyKurtaandPyjamaSet_W_Qxi2r3t.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647795037376",
    description: "Boys Festive & Party Kurta, Waistcoat and Pyjama Set",
    originalPrice: "3145",
    discountedPrice: "2516",
    rating: "3.2",
    totalRatings: "27",
    isAvailable: true,
    isWishlisted: false,
    isAddedToCart: false,
    availableSize: ["XS", "S", "L"],
    categoryName: "boys",
    count: "10",
  },
  {
    _id: uuid(),
    name: "Women Kurta",
    make: "Modern Attire",
    imgUrl:
      "https://ik.imagekit.io/tqp4crltjb5/Swadeshi-images/WomenSolidRayonStraightKurta_RcF58PVlq.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647795036723",
    description: "Women Solid Rayon Straight Kurta (Pink)",
    originalPrice: "1295",
    discountedPrice: "265",
    rating: "4.0",
    totalRatings: "800",
    isAvailable: true,
    isWishlisted: false,
    isAddedToCart: false,
    availableSize: ["XS", "S", "L", "XL", "XXL", "3XL"],
    categoryName: "women",
    count: "10",
  },
  {
    _id: uuid(),
    name: "Women Kurta",
    make: "STREE MANTRA",
    imgUrl:
      "https://ik.imagekit.io/tqp4crltjb5/Swadeshi-images/WomenFloralPrintGeorgetteKurta_-P2dSPYsok.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647795035115",
    description: "Women Floral Print Georgette A-line Kurta (Grey)",
    originalPrice: "1699",
    discountedPrice: "420",
    rating: "4.0",
    totalRatings: "4380",
    isAvailable: true,
    isWishlisted: false,
    isAddedToCart: false,
    availableSize: ["XS", "S", "L", "XL", "XXL", "3XL"],
    categoryName: "women",
    count: "10",
  },
];
